### ISSUE TITLE
Explore use of Minio for storage during development

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/archive-annotation#9]
Reference Example 
https://medium.com/@lionel.aimerie/elixir-phoenix-upload-management-s3-91bf611ce212

**Comment by aatmanvaidya** [comment]
@dennyabrain any specifc tasks or like an end-to-end prototype for this you can help me with?

since we already have a basic code setup, I can also just add a module for `MinIO`

do you want me to get started on this?

**Comment by dennyabrain** [comment]
You can start exploring for sure.

As for end to end prototype, let's do a simple file upload page. You drop a file, it gets uploaded to s3 and you log it's url. 

It's supposed to be a drop in replacement for s3 but there are steps like creating a bucket that we might have to do via a mix task.

**Comment by dennyabrain** [comment]
Found some sample code in another project that might be helpful

source : https://docs.hollo.social/install/docker/

Relevant portion
```yaml
  minio:
    image: minio/minio:RELEASE.2024-09-13T20-26-02Z
    ports:
    - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
    - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]

  create-bucket:
    image: minio/mc:RELEASE.2024-09-16T17-43-14Z
    depends_on:
    - minio
    entrypoint: |
      /bin/sh -c "
        /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
        /usr/bin/mc mb minio/hollo;
        /usr/bin/mc anonymous set public minio/hollo;
        exit 0;
      "
```
